### ISSUE TITLE
Not allow to retry errors with response < 500.

### ISSUE THREAD

**Issue by pazguille** [sindresorhus/is-retry-allowed#2]
The module allows to retry when an `error` is not defined, the `error.code` is not defined or the error is not included into the `WHITELIST` and `BLACKLIST. 

Therefore, if you have an error with response (404, 403, etc) the module is allowing to retry the operation.

**Comment by floatdrop** [comment]
@pazguille if error does not contain `code` – how module can decide to retry or not? From code side it looks like plain/network error and should be retried.

**Comment by sindresorhus** [comment]
@floatdrop I think the bug here is that Got switched from `.code` to `.statusCode`, but we forgot to update this module to support it. We also have some leftovers in https://github.com/sindresorhus/got/blob/a287f8ec8a6498d9d5e1037255b36946f5c0c97b/index.js#L329-L331.

**Comment by floatdrop** [comment]
@sindresorhus this is not a bug – this module checks `code` of error, but not `statusCode` of response. I'm quite sure, deciding retries based on `statusCode` should be done in user land.

**Comment by sindresorhus** [comment]
No, I meant the opposite, that 404 should not be retried, but it seems we don't even call this module in that situation. That makes me even more curious how @pazguille is able to get retrying with a 404.

**Comment by floatdrop** [comment]
@sindresorhus got ya.

@pazguille can you create issue in `got` repository instead?
